### PR TITLE
Prepare v0.1.3 semver-trick release for nb 1.0

### PR DESCRIPTION
**Pull request by eldruin**
The changelog for 1.0 does not contain the entry for 0.1.3, though. I could add it before the release in #33

### CODE REVIEW

**Comment by eldruin** [comment]
I am not sure I have done this right. Trying to build with a patched nb 1.0 via:
```toml
[patch.crates-io]
nb = { git = "http://github.com/eldruin/nb", branch = "prepare-1.0.0" }
```

it builds fine but trying to run the tests I get this error:
```
cargo +nightly test
    Updating git repository `http://github.com/eldruin/nb`
    Updating crates.io index
   Compiling nb v1.0.0 (http://github.com/eldruin/nb?branch=prepare-1.0.0#88eb3a04)
   Compiling nb v0.1.3 (/Users/eldruin/projects/rust/nb)
    Finished test [unoptimized + debuginfo] target(s) in 4.86s
     Running target/debug/deps/nb-8fff419367ff7817

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests nb
error[E0465]: multiple rlib candidates for `nb` found
   --> /Users/eldruin/projects/rust/nb/src/lib.rs:360:1
    |
360 | extern crate nb;
    | ^^^^^^^^^^^^^^^^
    |
note: candidate #1: /Users/eldruin/projects/rust/nb/target/debug/deps/libnb-c6e48575d4689b81.rlib
   --> /Users/eldruin/projects/rust/nb/src/lib.rs:360:1
    |
360 | extern crate nb;
    | ^^^^^^^^^^^^^^^^
note: candidate #2: /Users/eldruin/projects/rust/nb/target/debug/deps/libnb-d4482eca8b1336d7.rlib
   --> /Users/eldruin/projects/rust/nb/src/lib.rs:360:1
    |
360 | extern crate nb;
    | ^^^^^^^^^^^^^^^^

error[E0463]: can't find crate for `nb`
   --> /Users/eldruin/projects/rust/nb/src/lib.rs:360:1
    |
360 | extern crate nb;
    | ^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0463`.
error: test failed, to rerun pass '--doc'
```
Any ideas?

**Comment by eldruin** [comment]
Even with the published `nb = "1"` I am seeing the same error. What am I missing?

**Comment by eldruin** [comment]
I have not seen it documented anywhere but this seems like a known issue: https://github.com/rust-num/num-traits/blob/c9727a60511de4983a3083e94a6e2ca1f44ea3cc/Cargo.toml#L15

**Comment by eldruin** [comment]
Can I get a review here @rust-embedded/hal ?

**Comment by therealprof** [comment]
I guess we'll have to merge manually, there's no branch protection setup for this branch. 😅

**Comment by eldruin** [comment]
Thanks! could you publish the new version as well?

**Comment by therealprof** [comment]
Sure.

**Comment by therealprof** [comment]
Done.

**Comment by eldruin** [comment]
Awesome. Thank you!
